package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u341/2692/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, June 16, 2022 4:44:38 PM BST
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
     * This state indicates that the adapter is shutting down.
     */
  public static final short value = (short)(3);
}
