package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u341/2692/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Thursday, June 16, 2022 4:44:37 PM BST
*/


/**
    * DynEnum objects support the manipulation of IDL enumerated values.
    * The current position of a DynEnum is always -1.
    */
public interface DynEnum extends DynEnumOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynEnum
